# Generated by Django 4.1.1 on 2023-05-22 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="about",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="created",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="summary",
        ),
    ]
