# Generated by Django 4.1.1 on 2023-05-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="summary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
