# Generated by Django 4.1.1 on 2023-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_profile_about_profile_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
