# Generated by Django 4.1.1 on 2023-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created",
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
