# Generated by Django 4.1.1 on 2023-05-25 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_profile_friends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="friends",
            new_name="follows",
        ),
    ]
