# Generated by Django 4.1.1 on 2023-07-02 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="poll",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Poll",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
