# Generated by Django 4.1.1 on 2023-07-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="poll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.poll",
            ),
        ),
    ]
